### ISSUE TITLE
Error message is not correctly displayed for unauthorized users

### ISSUE THREAD

**Issue by xichen2020** [m3db/m3ctl#35]
cc @m-sandusky 

It seems the error message is not correctly displayed on the UI for unauthorized users when they attempt to create namespaces or rules. Can you please take a look when you get a chance?

**Comment by xichen2020** [comment]
Looks like other errors were written via `writeAPIResponse` in `r2/service.go` to marshal the errors, so perhaps we should do the same here?

**Comment by jskelcy** [comment]
I am seeing a content type that is not json coming back from the server. Ill take a look.

**Comment by jskelcy** [comment]
Here is a first pass at a fix
https://github.com/m3db/m3ctl/pull/36
We are on slightly rocky ground here with circular imports. But essentially the issue is that the auth layer is doing it own responding and now using the error handling set up in the r2 package. This was probably because of issues with circular imports.

**Comment by jskelcy** [comment]
Here is a first pass at a fix
https://github.com/m3db/m3ctl/pull/36
We are on slightly rocky ground here with circular imports. But essentially the issue is that the auth layer is doing it own responding and now using the error handling set up in the r2 package. This was probably because of issues with circular imports.
